### ISSUE TITLE
BOM C35 and CONN2 corrections

### ISSUE THREAD

**Issue by KDPate** [damienmaguire/Tesla-Charger#15]
C35 BOM definition is incorrect. CONN2 connector spec is out of date. Attached BOM with corrected callouts.

[Charger_Gen2_V2_BOM.zip](https://github.com/damienmaguire/Tesla-Charger/files/2583611/Charger_Gen2_V2_BOM.zip)

**Comment by damienmaguire** [comment]
Thank you. Uploaded to the repo.
