### ISSUE TITLE
Gen2TeslaChargerV4.ino doesn't work as expected

### ISSUE THREAD

**Issue by etuer** [damienmaguire/Tesla-Charger#20]
With auto start turned off (for basic testing without EVSE), the charger does not start on the 's' command as documented. 
There is a bug and it ends up in state 2 but no modules active.

See forum thread https://openinverter.org/forum/viewtopic.php?f=10&t=78&start=300

**Comment by damienmaguire** [comment]
Please read the comments at the top of the code :

-Added manual control mode for use of charger without EVSE. Digital one in when brought to +12v commands the charger to start
and when brought low commands charger off. This mode also control HVDC via digital out 1 and AC mains via a contactor via Digital out 2.-Working

**Comment by etuer** [comment]
It doesn't work as described in that comment either.
